print('Write your name:')
nombre=input()
print('Hello',nombre)
print('you are girl or boy')
gender=input()
print('you are a',gender)
print('Write your grade:')
grade=input()
print('Your grade is:',grade)
print('Write your favorite food:')
food=input()
print('is so delicious the :',food)
print('how do you feel:')
feel=input()
print('you feel',feel)
print('What sport do you practice')
sport=input()
print('the best sport is ',sport)
print('Were do you live')
country=input()
print('the best place is',country)
print('how tall are you')
size=input()
print('you are',size)
print('what is your skin color ')
color=input()
print('i like skin color',color)
print('are you fat or skinny')
fs=input()
print('if you are skinny good if not eat healthy,and you are:  ',fs)